import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { clearFlow, data, now, ruleSummary, type Rule } from "../crypto.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";

registerMainMenuItem({ label: "Alerts", data: "alerts:show:0", order: 30 });
const composer = new Composer<Ctx>();
const back = inlineKeyboard([[inlineButton("Back to alerts", "alerts:show:0")]]);
function id(): string { return `r${now().toString(36)}${Math.floor(now() % 997).toString(36)}`; }
async function coinPicker(ctx: Ctx) { const d = data(ctx); if (!d.watchlist.length) { await ctx.reply("Add a coin to your list before creating an alert.", { reply_markup: inlineKeyboard([[inlineButton("Add coin", "addcoin:start")]]) }); return; } await ctx.reply("Choose a tracked coin.", { reply_markup: inlineKeyboard([...d.watchlist.map((coin) => [inlineButton(`${coin.name} (${coin.symbol})`, `alert:coin:${coin.symbol}`)]), [inlineButton("Back to menu", "menu:main")]]) }); }
async function save(ctx: Ctx) { const p = ctx.session.pending; if (!p?.ticker || !p.type || p.window === undefined || p.ruleId === undefined) return; const d = data(ctx); const threshold = Number(p.ruleId); const cooldown = p.window; const rule: Rule = { id: id(), ticker: p.ticker, type: p.type, threshold, window: p.type === "percent" ? (p as typeof p & { percentWindow?: number }).percentWindow ?? 60 : 0, cooldown, active: true, createdAt: now() }; d.rules.push(rule); clearFlow(ctx); await ctx.reply(`Alert saved: ${ruleSummary(rule)}. It can trigger now; later alerts wait ${cooldown} hours.`, { reply_markup: inlineKeyboard([[inlineButton("View alerts", "alerts:show:0")]]) }); }
composer.callbackQuery("alert:create:start", async (ctx) => { await ctx.answerCallbackQuery(); clearFlow(ctx); await coinPicker(ctx); });
composer.callbackQuery(/^alerts:show:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const d = data(ctx); if (!d.rules.length) { await ctx.reply("No alerts yet — create one for a tracked coin.", { reply_markup: inlineKeyboard([[inlineButton("Create alert", "alert:create:start")]]) }); return; } const active = d.rules.filter((rule) => rule.active); await ctx.reply(`Your alerts\n${active.length ? active.map((rule) => `${ruleSummary(rule)} · every ${rule.cooldown}h`).join("\n") : "No active alerts."}`, { reply_markup: inlineKeyboard([...active.map((rule) => [inlineButton(`Disable ${rule.ticker}`, `alert:disable:${rule.id}`)]), [inlineButton("Create alert", "alert:create:start"), inlineButton("Back to menu", "menu:main")]]) }); });
composer.callbackQuery(/^alert:coin:([A-Z0-9]+)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.pending = { ticker: ctx.match[1] }; await ctx.reply(`Set an alert for ${ctx.match[1]}.`, { reply_markup: inlineKeyboard([[inlineButton("Price threshold", "alert:type:price")], [inlineButton("Percent change", "alert:type:percent")], [inlineButton("Back", "alert:create:start")]]) }); });
composer.callbackQuery(/^alert:type:(price|percent)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!ctx.session.pending) return; ctx.session.pending.type = ctx.match[1] as "price" | "percent"; if (ctx.match[1] === "price") { ctx.session.step = "price"; await ctx.reply("Send a USD target price greater than zero.", { reply_markup: { force_reply: true, input_field_placeholder: "Target price in USD" } }); } else { await ctx.reply("Choose the percent-change window.", { reply_markup: inlineKeyboard([[inlineButton("1 hour", "alert:window:60"), inlineButton("24 hours", "alert:window:1440")], [inlineButton("Custom window", "alert:window:custom")]]) }); } });
composer.callbackQuery(/^alert:window:(60|1440)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!ctx.session.pending) return; (ctx.session.pending as typeof ctx.session.pending & { percentWindow?: number }).percentWindow = Number(ctx.match[1]); ctx.session.step = "percent"; await ctx.reply("Send the percentage move to alert on. Use a negative number for a drop.", { reply_markup: { force_reply: true, input_field_placeholder: "For example: 5 or -5" } }); });
composer.callbackQuery("alert:window:custom", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "percentWindow"; await ctx.reply("Send a window in minutes, from 5 to 1440.", { reply_markup: { force_reply: true, input_field_placeholder: "Minutes" } }); });
composer.callbackQuery(/^alert:cooldown:(default|1|4|12|24)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!ctx.session.pending) return; const hours = ctx.match[1] === "default" ? data(ctx).profile.cooldown : Number(ctx.match[1]); ctx.session.pending.window = hours; await save(ctx); });
composer.on("message:text", async (ctx, next) => { const step = ctx.session.step; if (!step || !["price", "percent", "percentWindow"].includes(step)) return next(); const value = Number(ctx.message.text.trim()); if (!Number.isFinite(value)) { await ctx.reply("That isn't a number. Try again."); return; } if (step === "percentWindow") { if (value < 5 || value > 1440 || !Number.isInteger(value) || !ctx.session.pending) { await ctx.reply("Use a whole number from 5 to 1440 minutes."); return; } (ctx.session.pending as typeof ctx.session.pending & { percentWindow?: number }).percentWindow = value; ctx.session.step = "percent"; await ctx.reply("Send the percentage move to alert on. Use a negative number for a drop.", { reply_markup: { force_reply: true, input_field_placeholder: "For example: 5 or -5" } }); return; } if ((step === "price" && value <= 0) || (step === "percent" && (value === 0 || Math.abs(value) > 1000)) || !ctx.session.pending) { await ctx.reply(step === "price" ? "Use a price greater than zero." : "Use a percentage between -1000 and 1000, not zero."); return; } ctx.session.pending.ruleId = String(value); ctx.session.step = "cooldown"; await ctx.reply(`Choose a cooldown after this alert fires. Your default is ${data(ctx).profile.cooldown} hours.`, { reply_markup: inlineKeyboard([[inlineButton("Use default", "alert:cooldown:default"), inlineButton("1 hour", "alert:cooldown:1")], [inlineButton("4 hours", "alert:cooldown:4"), inlineButton("12 hours", "alert:cooldown:12")], [inlineButton("24 hours", "alert:cooldown:24")]]) }); });
composer.callbackQuery(/^alert:disable:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const rule = data(ctx).rules.find((item) => item.id === ctx.match[1]); if (!rule) { await ctx.reply("That alert is no longer available."); return; } rule.active = false; await ctx.editMessageText("Alert disabled.", { reply_markup: back }); });
export default composer;
